openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is the API documentation for Task Pro App.
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
    post:
      $ref: ../swagger/paths/users/post.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/getCurrentUser.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/users/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/users/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
